services:

  nginx:

    image: nginx:alpine

    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - python

    networks:
      - application


  python:

    image: ${PYTHON_IMAGE}

    restart: unless-stopped

    networks:
      - application


networks:

  application:

    name: application

    driver: bridge